version: "3.8"

services:
  ibm-mq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: ibm-mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: adminpass
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - mq-data:/mnt/mqm
      - ./config.mqsc:/etc/mqm/config.mqsc
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock



volumes:
  mq-data:
  jenkins_home: